---
- name: Transfer and install p2pool.
  hosts: monero
  become: true
  remote_user: ubuntu
  become_method: ansible.builtin.sudo

  tasks:
    - name: Run make_monero script
      ansible.builtin.script: scripts/add_p2pool.sh
      args:
        creates: /usr/local/bin/p2pool

    - name: Add systemd xmrig unit file
      ansible.builtin.copy:
        src: conf/p2pool.service
        dest: /etc/systemd/system/p2pool.service
        owner: root
        group: root
        mode: '0644'

    - name: Enable p2pool systemd
      ansible.builtin.systemd:
        name: p2pool
        state: started
        masked: false
        enabled: true
