---
- name: Transfer and install monerod.
  hosts: add-monero
  become: true
  remote_user: ubuntu
  become_method: ansible.builtin.sudo

  tasks:
    - name: script1
      ansible.builtin.copy: src=monero.service dest=/etc/systemd/system/monero.service mode=0755

    - name: script2
      ansible.builtin.copy: src=make_monero.sh dest=/home/ubuntu/make_monero.sh mode=0755

    - name: script3
      ansible.builtin.copy: src=monerod.conf dest=/etc/monero/monerod.conf

    - name: Install bzip2
      ansible.builtin.apt:
        name: bzip2
        state: present

    - name: Run a script only if file.txt does not exist on the remote node
      ansible.builtin.script: ./make_monero.sh
      
