---
- name: Transfer and install xmrig.
  hosts: monero
  become: true
  remote_user: ubuntu
  become_method: ansible.builtin.sudo

  tasks:
    - name: Run add_xmrig script
      ansible.builtin.script: scripts/add_xmrig.sh
      args:
        creates: /usr/local/bin/xmrig

    - name: Add systemd xmrig unit file
      ansible.builtin.copy:
        src: conf/xmrig.service
        dest: /etc/systemd/system/xmrig.service
        owner: root
        group: root
        mode: '0644'
        force: true

    - name: Systemctl daemon-reload xmrig
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Enable xmrig systemd
      ansible.builtin.systemd:
        name: xmrig
        state: restarted
        daemon_reload: true
        masked: false
        enabled: true
