k3s_cluster:
  hosts:
    j1:
    hippy:
    hippy01:
    hippy02:
    lenny:
    puck:
    pi4:

arm64:
  hosts:
    pi4:

monero:
  hosts:
    j1:
    hippy:
    hippy01:
    hippy02:
    lenny:
    puck:
    e455:

x86:
  hosts:
    hippy:
    hippy01:
    hippy02:
    lenny:
    puck:
    j1:
