---
- name: Enable monerod systemd service
  hosts: all
  become: true
  remote_user: ubuntu
  gather_facts: true

  tasks:
    - name: Enable monerod systemd
      ansible.builtin.systemd_service:
        name: monerod
        enabled: true
        state: started
        masked: false
