---
- name: Make Monero
  hosts: all
  # gather_fats after python is found
  gather_facts: false
  vars:
    ansible_bender:
      base_image: 'docker.io/library/ubuntu:23.10'
      buildah_from_extra_args: "--dns 8.8.8.8"
      ansible_extra_args: "-vvv -c ./ansible.cfg"
      target_image:
        name: "p2pool"
        cmd: bash
        entrypoint: 'nohup /entrypoint.sh &'
        environment:
          wallet_addr: '4B4b'

      cache_tasks: true
      layering: true
      squash: true
      verbose_layer_names: true

      working_container:
        entrypoint: 'nohup /entrypoint.sh &'

  tasks:
  # Installing python3 via raw and apt while I find the intermittent python3-not-found bug
    - name: Bootstrap a host without python3 installed
      ansible.builtin.raw: '/usr/bin/apt-get update && /usr/bin/apt-get -y install python3'
      args:
        executable: /bin/bash

    - name: Make sure python3 gpg and wget are installed
      package:
        name:
          - python3
          - wget
          - gpg
          - bzip2
          - libdigest-sha-perl
          - sudo
        state: present

    - name: Gather facts after Python runtime is available
      setup:
        gather_subset:
          - '!all'
          - '!<any valid subset>'
          - facter

    - name: Ensure group monero exists
      group:
        name: monero
        state: present

    - name: Create a login user
      ansible.builtin.user:
        name: monero
        # password: 'CHANGEME'
        groups:
          - monero
        state: present
        shell: /bin/bash
        system: true
        createhome: true
        home: /var/lib/monero

    - name: Create etc-monero
      ansible.builtin.file:
        path: /etc/monero
        state: directory
        group: monero
        owner: monero
        mode: "0710"
        recurse: true

    - name: Create var-run-monero
      ansible.builtin.file:
        path: /var/run/monero
        state: directory
        group: monero
        owner: monero
        mode: "0644"
        recurse: true

    - name: Create var-log-monero
      ansible.builtin.file:
        path: /var/log/monero
        state: directory
        group: monero
        owner: monero
        mode: "0644"
        recurse: true

    - name: Create var-lib-monero
      ansible.builtin.file:
        path: /var/lib/monero/.bitmonero
        state: directory
        group: monero
        owner: monero
        mode: "0744"
        recurse: true

    - name: Copy etc-monerod.conf
      ansible.builtin.copy:
        src: ./conf/monerod.conf
        dest: /etc/monero/monerod.conf
        owner: monero
        group: monero
        mode: "0644"
        force: true

    - name: Copy entrypoint.sh
      ansible.builtin.copy:
        src: ./scripts/entrypoint.sh
        dest: /entrypoint.sh
        owner: monero
        group: monero
        mode: "0555"
        force: true
    - name: Show permissions
      ansible.builtin.raw: 'ls -all && id'
      args:
        executable: /bin/bash

    - name: Run add_monero script
      ansible.builtin.script: ./scripts/add_monero_docker.sh
      args:
        creates: /usr/local/bin/monerod

    - name: Run p2pool installer
      ansible.builtin.script: scripts/add_p2pool_docker.sh
      args:
        creates: /usr/local/bin/p2pool

    - name: Run add_xmrig installer
      ansible.builtin.script: scripts/add_xmrig_docker.sh
      args:
        creates: /usr/local/bin/xmrig
