---
- name: Gather CPU RAM and Disk Space Usage
  hosts: monero
  become: true
  remote_user: ubuntu
  gather_facts: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Gather CPU usage
      ansible.builtin.shell:
        cmd: set -o pipefail && top -bn1 | grep 'Cpu(s)' | awk '{print $2}'
        executable: /bin/bash
      register: cpu_usage
      changed_when: cpu_usage.rc != 0

    - name: Gather RAM Usage
      ansible.builtin.shell:
        cmd: set -o pipefail && top -bn1 | awk '/MiB Mem/ {printf "%.2f\n", $8/$4 * 100}'
        executable: /bin/bash
      register: ram_usage
      changed_when: ram_usage.rc != 0

    - name: Gather Disk Space
      ansible.builtin.shell:
        cmd: set -o pipefail && df -h --output=pcent / | awk 'NR==2 {print $1}'
        executable: /bin/bash
      register: disk_space
      changed_when: disk_space.rc != 0

    - name: Gather P2P logs
      ansible.builtin.shell:
        cmd: set -o pipefail && grep -i xmrig /var/log/syslog |tail -2
        executable: /bin/bash
      register: monero_logs
      changed_when: monero_logs.rc != 0

    - name: Get CPU usage
      ansible.builtin.shell:
        cmd: set -o pipefail && top -b -n 1
        executable: /bin/bash
      register: top
      changed_when: top.rc != 0

    - name: Get H/s
      ansible.builtin.shell:
        cmd: set -o pipefail && grep "H/s" /var/log/syslog |tail -1
        executable: /bin/bash
      register: hashsecs
      changed_when: hashsecs.rc != 0

    - name: Set CPU usage facts
      ansible.builtin.set_fact:
        user_cpu: "{{ top.stdout_lines[2].split()[1] }}"
        system_cpu: "{{ top.stdout_lines[2].split()[3] }}"

    - name: Usage Stats
      ansible.builtin.debug:
        msg:
          - "Executed On: {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
          - "CPU Usage: {{ cpu_usage.stdout }}%"
          - "User CPU usage: {{ user_cpu }}"
          - "System CPU usage: {{ system_cpu }}"
          - "RAM Usage: {{ ram_usage.stdout }}%"
          - "Disk Space Used: {{ disk_space.stdout }}"
          - "Monero-log: {{ monero_logs.stdout }}"
          - "H/s: {{ hashsecs.stdout }}"
