---
- name: Gather CPU RAM and Disk Space Usage
  hosts: monero
  become: true
  remote_user: ubuntu
  gather_facts: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Gather CPU usage
      ansible.builtin.shell: top -bn1 | grep 'Cpu(s)' | awk '{print $2}'
      register: cpu_usage
    - name: Gather RAM Usage
      ansible.builtin.shell: top -bn1 | awk '/MiB Mem/ {printf "%.2f\n", $8/$4 * 100}'
      register: ram_usage
    - name: Gather Disk Space
      ansible.builtin.shell: "df -h --output=pcent / | awk 'NR==2 {print $1}'"
      register: disk_space
    - name: Gather P2P logs
      ansible.builtin.shell: grep P2P /var/log/monero/monerod.log |tail -5
      register: monero_logs
    - name: Usage Stats
      debug:
        msg: 
          - "Executed On: {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
          - "CPU Usage: {{ cpu_usage.stdout }}%"
          - "RAM Usage: {{ ram_usage.stdout }}%"
          - "Disk Space Used: {{ disk_space.stdout }}"
          - "Monero-log: {{ monero_logs.stdout }}"